name: Backup DB

on:
  schedule:
    - cron: "* * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: curl "${{ secrets.BASE_URL }}/api/backup" --request POST --create-dirs --output backup/data.json.gz
      - run: |
          git config --local user.email "abhayvashokan@gmail.com"
          git config --local user.name "Abhay V Ashokan"
          git add -A
          if [[ -n $(git status --porcelain) ]]; then
              git commit -m "Backup $(date +%F)"
              git push --no-verify
          fi
