name: CI check

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: git fetch origin main 2> /dev/null
      - run: git diff-tree --diff-filter=a -r --no-commit-id --name-only HEAD remotes/origin/main | grep --color=none -i -e "\.js$" -e "\.jsx$" -e "\.ts$" -e "\.tsx$" | awk '!/.eslintrc.js/ {print}' | xargs npx eslint --no-error-on-unmatched-pattern
      - run: bun run build
