name: CI check

on:
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          node-version-file: ".nvmrc"
      # Run ESlint on modified files.
      - run: bun install
      - run: git fetch origin main 2> /dev/null
      - run: git diff-tree --diff-filter=a -r --no-commit-id --name-only HEAD remotes/origin/main | grep --color=none -i -e "\.js$" -e "\.jsx$"| awk '!/.eslintrc.js/ {print}' | xargs npx eslint --no-error-on-unmatched-pattern
