name: Sync problems

on:
  schedule:
    # Every hour between 8:30AM and 1:30AM IST.
    - cron: "0 3-20 * * *"

jobs:
  sync:
    runs_on: ubuntu-latest

    steps:
    run: curl --request POST "${{ BASE_URL }}/api/sync"
