name: Sync problems

on:
  schedule:
    # Every hour between 8:30AM and 1:30AM IST.
    - cron: "25 3-20 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - run: curl --request POST "${{ secrets.BASE_URL }}/api/sync"
